-- Add missing columns to settings table to match local SQLite schema

-- First, change id from UUID to TEXT since local SQLite uses '1' as the id
ALTER TABLE settings ALTER COLUMN id TYPE TEXT USING id::text;

-- Add sync framework columns that are missing from settings
ALTER TABLE settings 
    ADD COLUMN IF NOT EXISTS sync_status TEXT DEFAULT 'PENDING',
    ADD COLUMN IF NOT EXISTS version INTEGER DEFAULT 1,
    ADD COLUMN IF NOT EXISTS device_id TEXT,
    ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

-- Add Business Profile & Branding columns
ALTER TABLE settings
    ADD COLUMN IF NOT EXISTS name TEXT,
    ADD COLUMN IF NOT EXISTS name_urdu TEXT,
    ADD COLUMN IF NOT EXISTS address TEXT,
    ADD COLUMN IF NOT EXISTS address_urdu TEXT,
    ADD COLUMN IF NOT EXISTS phone TEXT,
    ADD COLUMN IF NOT EXISTS email TEXT,
    ADD COLUMN IF NOT EXISTS tax_rate REAL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS logo TEXT,
    ADD COLUMN IF NOT EXISTS website TEXT,
    ADD COLUMN IF NOT EXISTS tax_registration_number TEXT,
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS invoice_logo TEXT;

-- Add Localization & Tax columns
ALTER TABLE settings
    ADD COLUMN IF NOT EXISTS language TEXT,
    ADD COLUMN IF NOT EXISTS time_zone TEXT,
    ADD COLUMN IF NOT EXISTS tax_rates_json TEXT,
    ADD COLUMN IF NOT EXISTS tax_inclusive TEXT,
    ADD COLUMN IF NOT EXISTS tax_exclusive TEXT,
    ADD COLUMN IF NOT EXISTS invoice_tax_display TEXT;

-- Add Receipt layout columns
ALTER TABLE settings
    ADD COLUMN IF NOT EXISTS watermark TEXT,
    ADD COLUMN IF NOT EXISTS store_name TEXT,
    ADD COLUMN IF NOT EXISTS branch_name TEXT,
    ADD COLUMN IF NOT EXISTS tagline TEXT,
    ADD COLUMN IF NOT EXISTS receipt_background TEXT,
    ADD COLUMN IF NOT EXISTS show_header_business_name TEXT,
    ADD COLUMN IF NOT EXISTS show_header_branch TEXT,
    ADD COLUMN IF NOT EXISTS show_header_address TEXT,
    ADD COLUMN IF NOT EXISTS show_header_phone TEXT,
    ADD COLUMN IF NOT EXISTS show_header_email TEXT,
    ADD COLUMN IF NOT EXISTS show_header_website TEXT,
    ADD COLUMN IF NOT EXISTS show_header_ntn TEXT,
    ADD COLUMN IF NOT EXISTS show_header_strn TEXT,
    ADD COLUMN IF NOT EXISTS show_header_gst TEXT,
    ADD COLUMN IF NOT EXISTS show_header_qr TEXT,
    ADD COLUMN IF NOT EXISTS show_header_social TEXT,
    ADD COLUMN IF NOT EXISTS show_invoice_number TEXT,
    ADD COLUMN IF NOT EXISTS show_date TEXT,
    ADD COLUMN IF NOT EXISTS show_time TEXT,
    ADD COLUMN IF NOT EXISTS show_cashier TEXT,
    ADD COLUMN IF NOT EXISTS show_customer_name TEXT,
    ADD COLUMN IF NOT EXISTS show_customer_phone TEXT,
    ADD COLUMN IF NOT EXISTS show_customer_address TEXT,
    ADD COLUMN IF NOT EXISTS show_membership TEXT,
    ADD COLUMN IF NOT EXISTS show_payment_method TEXT,
    ADD COLUMN IF NOT EXISTS show_counter_number TEXT,
    ADD COLUMN IF NOT EXISTS show_terminal TEXT,
    ADD COLUMN IF NOT EXISTS show_order_notes TEXT,
    ADD COLUMN IF NOT EXISTS show_product_name TEXT,
    ADD COLUMN IF NOT EXISTS show_sku TEXT,
    ADD COLUMN IF NOT EXISTS show_brand TEXT,
    ADD COLUMN IF NOT EXISTS show_category TEXT,
    ADD COLUMN IF NOT EXISTS show_quantity TEXT,
    ADD COLUMN IF NOT EXISTS show_unit_price TEXT,
    ADD COLUMN IF NOT EXISTS show_product_discount TEXT,
    ADD COLUMN IF NOT EXISTS show_product_tax TEXT,
    ADD COLUMN IF NOT EXISTS show_serial_number TEXT,
    ADD COLUMN IF NOT EXISTS show_batch_number TEXT,
    ADD COLUMN IF NOT EXISTS show_expiry_date TEXT,
    ADD COLUMN IF NOT EXISTS show_variant TEXT,
    ADD COLUMN IF NOT EXISTS product_view_mode TEXT,
    ADD COLUMN IF NOT EXISTS show_subtotal TEXT,
    ADD COLUMN IF NOT EXISTS show_total_discount TEXT,
    ADD COLUMN IF NOT EXISTS show_coupons TEXT,
    ADD COLUMN IF NOT EXISTS show_total_tax TEXT,
    ADD COLUMN IF NOT EXISTS show_service_charges TEXT,
    ADD COLUMN IF NOT EXISTS show_delivery_charges TEXT,
    ADD COLUMN IF NOT EXISTS show_tips TEXT,
    ADD COLUMN IF NOT EXISTS show_cash_received TEXT,
    ADD COLUMN IF NOT EXISTS show_change_returned TEXT,
    ADD COLUMN IF NOT EXISTS show_grand_total TEXT,
    ADD COLUMN IF NOT EXISTS show_loyalty_points TEXT,
    ADD COLUMN IF NOT EXISTS show_gift_card_balance TEXT,
    ADD COLUMN IF NOT EXISTS exchange_policy TEXT,
    ADD COLUMN IF NOT EXISTS refund_policy TEXT,
    ADD COLUMN IF NOT EXISTS warranty_policy TEXT,
    ADD COLUMN IF NOT EXISTS terms_and_conditions TEXT,
    ADD COLUMN IF NOT EXISTS social_facebook TEXT,
    ADD COLUMN IF NOT EXISTS social_instagram TEXT,
    ADD COLUMN IF NOT EXISTS social_whatsapp TEXT;

-- Add Print and Digital Receipt columns
ALTER TABLE settings
    ADD COLUMN IF NOT EXISTS print_copies TEXT,
    ADD COLUMN IF NOT EXISTS print_customer_copy TEXT,
    ADD COLUMN IF NOT EXISTS print_merchant_copy TEXT,
    ADD COLUMN IF NOT EXISTS print_kitchen_copy TEXT,
    ADD COLUMN IF NOT EXISTS print_silent TEXT,
    ADD COLUMN IF NOT EXISTS print_auto_cut TEXT,
    ADD COLUMN IF NOT EXISTS print_beep TEXT,
    ADD COLUMN IF NOT EXISTS default_printer TEXT,
    ADD COLUMN IF NOT EXISTS connection_type TEXT,
    ADD COLUMN IF NOT EXISTS printer_encoding TEXT,
    ADD COLUMN IF NOT EXISTS digital_receipt_email TEXT,
    ADD COLUMN IF NOT EXISTS digital_receipt_sms TEXT,
    ADD COLUMN IF NOT EXISTS digital_receipt_whatsapp TEXT,
    ADD COLUMN IF NOT EXISTS digital_receipt_pdf TEXT,
    ADD COLUMN IF NOT EXISTS digital_receipt_customer_portal TEXT,
    ADD COLUMN IF NOT EXISTS attach_pdf_automatically TEXT,
    ADD COLUMN IF NOT EXISTS qr_type TEXT,
    ADD COLUMN IF NOT EXISTS qr_website_url TEXT,
    ADD COLUMN IF NOT EXISTS barcode_size TEXT,
    ADD COLUMN IF NOT EXISTS receipt_font TEXT,
    ADD COLUMN IF NOT EXISTS receipt_character_density TEXT;

-- Add SKU and Barcode Settings
ALTER TABLE settings
    ADD COLUMN IF NOT EXISTS auto_sku_generation TEXT,
    ADD COLUMN IF NOT EXISTS sku_format TEXT,
    ADD COLUMN IF NOT EXISTS sku_workspace_prefix TEXT,
    ADD COLUMN IF NOT EXISTS sku_store_prefix TEXT,
    ADD COLUMN IF NOT EXISTS sku_category_prefix TEXT,
    ADD COLUMN IF NOT EXISTS sku_brand_prefix TEXT,
    ADD COLUMN IF NOT EXISTS sku_prefix_separator TEXT,
    ADD COLUMN IF NOT EXISTS sku_starting_number TEXT,
    ADD COLUMN IF NOT EXISTS sku_number_length TEXT,
    ADD COLUMN IF NOT EXISTS sku_increment_by TEXT,
    ADD COLUMN IF NOT EXISTS auto_barcode_generation TEXT,
    ADD COLUMN IF NOT EXISTS barcode_type TEXT,
    ADD COLUMN IF NOT EXISTS barcode_prefix TEXT,
    ADD COLUMN IF NOT EXISTS barcode_starting_number TEXT,
    ADD COLUMN IF NOT EXISTS barcode_length TEXT,
    ADD COLUMN IF NOT EXISTS barcode_increment_by TEXT,
    ADD COLUMN IF NOT EXISTS sku_counter TEXT,
    ADD COLUMN IF NOT EXISTS barcode_counter TEXT,
    ADD COLUMN IF NOT EXISTS prevent_duplicate_sku TEXT,
    ADD COLUMN IF NOT EXISTS prevent_duplicate_barcode TEXT,
    ADD COLUMN IF NOT EXISTS validate_during_import TEXT,
    ADD COLUMN IF NOT EXISTS auto_detect_conflicts TEXT,
    ADD COLUMN IF NOT EXISTS auto_suggest_next_available_number TEXT,
    ADD COLUMN IF NOT EXISTS highlight_duplicate_ids TEXT,
    ADD COLUMN IF NOT EXISTS allow_manual_sku TEXT,
    ADD COLUMN IF NOT EXISTS allow_manual_barcode TEXT,
    ADD COLUMN IF NOT EXISTS default_label_size TEXT,
    ADD COLUMN IF NOT EXISTS label_orientation TEXT,
    ADD COLUMN IF NOT EXISTS include_product_name_label TEXT,
    ADD COLUMN IF NOT EXISTS include_price_label TEXT,
    ADD COLUMN IF NOT EXISTS include_sku_label TEXT,
    ADD COLUMN IF NOT EXISTS include_barcode_label TEXT,
    ADD COLUMN IF NOT EXISTS include_brand_label TEXT,
    ADD COLUMN IF NOT EXISTS include_category_label TEXT,
    ADD COLUMN IF NOT EXISTS include_logo_label TEXT,
    ADD COLUMN IF NOT EXISTS print_quantity_default TEXT,
    ADD COLUMN IF NOT EXISTS default_barcode_font_size TEXT,
    ADD COLUMN IF NOT EXISTS scanner_optimization TEXT,
    ADD COLUMN IF NOT EXISTS default_unit TEXT,
    ADD COLUMN IF NOT EXISTS sku_generation_pattern TEXT,
    ADD COLUMN IF NOT EXISTS auto_product_code TEXT;

-- Add POS and Appearance settings
ALTER TABLE settings
    ADD COLUMN IF NOT EXISTS default_payment_method TEXT,
    ADD COLUMN IF NOT EXISTS default_customer_type TEXT,
    ADD COLUMN IF NOT EXISTS default_discount_behavior TEXT,
    ADD COLUMN IF NOT EXISTS low_stock_alerts TEXT,
    ADD COLUMN IF NOT EXISTS purchase_alerts TEXT,
    ADD COLUMN IF NOT EXISTS sales_alerts TEXT,
    ADD COLUMN IF NOT EXISTS customer_balance_alerts TEXT,
    ADD COLUMN IF NOT EXISTS supplier_payment_alerts TEXT,
    ADD COLUMN IF NOT EXISTS system_notifications TEXT,
    ADD COLUMN IF NOT EXISTS desktop_notifications TEXT,
    ADD COLUMN IF NOT EXISTS system_theme TEXT,
    ADD COLUMN IF NOT EXISTS compact_mode TEXT,
    ADD COLUMN IF NOT EXISTS comfortable_mode TEXT,
    ADD COLUMN IF NOT EXISTS sidebar_behavior TEXT,
    ADD COLUMN IF NOT EXISTS dashboard_density TEXT,
    ADD COLUMN IF NOT EXISTS shortcut_new_sale TEXT,
    ADD COLUMN IF NOT EXISTS shortcut_add_product TEXT,
    ADD COLUMN IF NOT EXISTS shortcut_search TEXT,
    ADD COLUMN IF NOT EXISTS shortcut_print_receipt TEXT,
    ADD COLUMN IF NOT EXISTS shortcut_save TEXT,
    ADD COLUMN IF NOT EXISTS shortcut_dashboard TEXT,
    ADD COLUMN IF NOT EXISTS shortcut_reports TEXT,
    ADD COLUMN IF NOT EXISTS auto_save TEXT,
    ADD COLUMN IF NOT EXISTS auto_refresh TEXT,
    ADD COLUMN IF NOT EXISTS default_landing_page TEXT,
    ADD COLUMN IF NOT EXISTS number_precision TEXT,
    ADD COLUMN IF NOT EXISTS search_behavior TEXT,
    ADD COLUMN IF NOT EXISTS table_density TEXT,
    ADD COLUMN IF NOT EXISTS session_timeout TEXT,
    ADD COLUMN IF NOT EXISTS auto_logout TEXT,
    ADD COLUMN IF NOT EXISTS device_remembering TEXT,
    ADD COLUMN IF NOT EXISTS password_policy TEXT;
